- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.3
  hooks:
  - id: autopep8
- repo: git@github.com:pre-commit/pre-commit-hooks.git
  rev: v2.0.0
  hooks:
  - id: check-added-large-files
  #- id: flake8
  - id: requirements-txt-fixer
  - id: trailing-whitespace
