language: python
dist: xenial
sudo: required
python:
  - "3.6"
  - "3.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create environment and add any dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest pytest-cov
  - source activate test-environment
  - pip install codecov

script:
  - pip install -e .
  - pytest -v --cov=chemreps tests/

after_success:
  - codecov

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aa8992fdb8cf0736101c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
